version: '3.7'

services:
  docker-deploy:
    image: ghcr.io/ozeliurs/dockerdeploy:latest
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docker-deploy.rule=Host(`dockerdeploy.ozeliurs.com`)"
      - "traefik.http.routers.docker-deploy.entrypoints=websecure"
      - "traefik.http.routers.docker-deploy.tls.certresolver=cloudflare"
      - "traefik.http.routers.docker-deploy.tls=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs

networks:
  traefik:
    external: true